language: python

python:
  - "3.3"

install:
  - "pip install ."

script:
  - "py.test tests"

notifications:
  irc:
    channels:
    - "irc.ozinger.org#khris"
    on_success: change
    on_failure: always
